### PR TITLE
How do I install this in VS 2017?

### PR DESCRIPTION
**Pull request by dydx-git**
So.. I know it's really stupid to create a pull request just to ask this but I couldn't find a way to contact you.. Can you please tell me how do I install and use this library in my CSharp Project?

Thanks!

### CODE REVIEW

**Comment by PipatPosawad** [comment]
Right click on your project file in Solution explorer
Select Manage Nuget Packages...
Search for "Chronic" and select it
Click on install button

**Comment by dydx-git** [comment]
Will that package be from robertwilczynski or dorony? Because dorony's package got a few bug fixes ^_^

**Comment by PipatPosawad** [comment]
In the NuGet, It is from robertwilczynski.

**Comment by PipatPosawad** [comment]
If you want Chronic from dorony, you have to download from dorony.
https://github.com/dorony/nChronic
and build this project by yourself.

**Comment by dydx-git** [comment]
Can you please find me a tutorrial on how to build this? You might think that I'm just being lazy but I don't really kow what to search for... =/

Thank you for your help!

**Pull request closed without merging**
